# Dependencies
markdown:	kramdown
# Permalinks
permalink:	:title/

# Setup
title:            취향의 흔적
tagline:          'blog'
description:      'My personal blog.'
url:              http://resistan.com
baseurl:          
commentsystem:    disqus
disqus:           resistan
include:          [_pages]
default_locale:   "ko"

author:
  name:           resistan
  url:            https://resistan.com

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            https://lh3.googleusercontent.com/QDeFRg2oF-LWKsE5i_4qw9TKzGCQQEFBr27WciBy47MY6js2gKNLGBUo4IJ3pG7okwyZm4NQgCxaq079O7rRAejR9rQsUy28w76GSPMU3dg4T8PHhC6tG8TmZtNwVzE-5dLB-CJmpIamXfPq4nxmq2R47V-0i1jpNkh2C9orbcCOGhjat63ugi9mMDzA0W5dsfkev7PotbT_jl4CkPR-cTACGXikr46mpJwal4rtpkeQNPsUwSVs4Edbplfb55lIjS6FiR2LN93mjY6dvtGZxp25_U9K7j6cp4-B3UaJXSQFku76i5fofRNZEuC4oE_dLaLpyTMQVvYsXfG7EHFXuFUEjDsIZD9t_XkGtvnfnVT8bPTq-Ty7_BsESKZ2Cn3Jz4J68xVKy_b5vT8jxmxloaZ4O-QLhT4IFGQiP7h9cylLg39kcg76wenaAXz_UjLevdnD7OFEgPnkNFJRAfKibcxY6Hg_2OxzuhXcQl9AlIXgiN9npVPU6yWbMpKZSk7uj-B6SFSRRPF7jEgnhgTaffA_r5f9gWo6KKVO0rv6NqY7FQBpkNR5tl-ETnPjp2TgQsoJyM3hPaDZZJvHdDRZye8C5hWQILZhpgSxwg99kwKSKTq5PjkIISrwazKAIU5_-Uomz6zTEEnPOgfe9ROYG_cM7xZJj5A5SwZ6q9l-0eX30M4=w1505-h1007-no

social:
  - icon:         facebook
    url:          https://facebook.com/hj.soif
    desc:         Follow me on facebook
  - icon:         twitter
    url:          https://twitter.com/resistan
    desc:         Follow me on twitter
  - icon:         github
    url:          https://github.com/resistan
    desc:         Fork me on github
  # - icon:         googleplus-alt
  #   url:          https://google.com/+IanCamporezBrunelli
  #   desc:         Add me on google+
  - icon:         feed
    url:          http://resistan.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        "처음"
    url:          /
  - title:        "소개"
    url:          /about-me
  - title:       "전체 글 모음"
    url:          /archives
  # - title:       "검색"
  #   url:          /search
  # - title:       "방명록"
  #   url:          /guestbook
  - title:       "개발자 좀 살려주세요"
    url:          /savethedeveloper/

copyright:
  author:         resistan
  url:            http://resistan.com
  type_title:     Some rights reserved
  type_url:       https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ko

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-251544-2

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576

gems: [jekyll-paginate]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from